version: '3.7'
services:
  #Postgres-DB
  postgres-server:
    image: postgres:latest
    container_name: postgres-server
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-zabbix_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-zabbix_pass}
      - POSTGRES_DB=zabbix
    networks:
      - zabbix-net
    restart: always
    
  #snmptraps
  zabbix-snmptraps:
    image: zabbix/zabbix-snmptraps:alpine-7.0-latest
    container_name: zabbix-snmptraps
    volumes:
      - /zbx_instance/snmptraps:/var/lib/zabbix/snmptraps:rw
      - /var/lib/zabbix/mibs:/usr/share/snmp/mibs:ro
    networks:
      - zabbix-net
    ports:
      - "162:1162/udp"
    restart: always

  #Zabbix-Postgres-Server
  zabbix-server-pgsql:
    image: zabbix/zabbix-server-pgsql:alpine-7.0-latest
    container_name: zabbix-server-pgsql
    environment:
      - DB_SERVER_HOST=postgres-server 
      - POSTGRES_USER=${POSTGRES_USER:-zabbix_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-zabbix_pass}
      - POSTGRES_DB=zabbix
      - ZBX_ENABLE_SNMP_TRAPS="true"
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - zabbix-net
    ports:
      - "10051:10051"
    volumes_from:
      - zabbix-snmptraps
    restart: always

  #Nginx-Web
  zabbix-web-nginx-pgsql:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-7.0-latest
    container_name: zabbix-web-nginx-pgsql
    environment:
      - ZBX_SERVER_HOST=zabbix-server-pgsql
      - DB_SERVER_HOST=postgres-server
      - POSTGRES_USER=${POSTGRES_USER:-zabbix_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-zabbix_pass}
      - POSTGRES_DB=zabbix
    networks:
      - zabbix-net
    ports:
      - "443:8443"
      - "8080:8080"
    volumes:
      - /etc/ssl/nginx:/etc/ssl/nginx:ro
    restart: always

  #Agent2
  zabbix-agent2:
    image: zabbix/zabbix-agent2:alpine-7.0-latest
    container_name: zabbix-agent2
    environment:
      - ZBX_SERVER_HOST=zabbix-server-pgsql
      - ZBX_HOSTNAME=${ZBX_AGENT2_HOSTNAME:-zabbix-agent2}
      - ZBX_LISTENPORT=${ZBX_AGENT2_LISTENPORT:-10049}
    networks:
      - zabbix-net
    ports:
      - "10049:10049"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    privileged: true
    user: "0"  # Run the container as root (optional)

networks:
  zabbix-net:
    name: zabbix-net
    driver: bridge

