version: '3.7'
services:
  zabbix-agent2:
    image: zabbix/zabbix-agent2:alpine-7.0-latest
    container_name: zabbix-agent2
    environment:
      - ZBX_SERVER_HOST=${ZBX_SERVER_HOST}
      - ZBX_HOSTNAME=${ZBX_AGENT2_HOSTNAME}
      - ZBX_LISTENPORT=${ZBX_AGENT2_LISTENPORT}
    networks:
      - zabbix-net
    ports:
      - "10049:10049"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    privileged: true
    user: "0"  # Run the container as root (optional)
networks:
  zabbix-net:
    name: zabbix-net
    driver: bridge